sudo: required

# clang-3.5 or later required to support -std=c++14.
# http://clang.llvm.org/cxx_status.html
addons:
    apt:
        sources:
            - llvm-toolchain-precise
            - ubuntu-toolchain-r-test
        packages:
            - clang-5.0

language: cpp

compiler:
  - clang-5.0

script:
  - mkdir out
  - cd out
  - cmake ..
  - make
  - ./dux_fixed_test_bin