sudo: required

# clang-3.5 or later required to support -std=c++14.
# http://clang.llvm.org/cxx_status.html
addons:
    apt:
        sources:
            - llvm-toolchain-precise
            - ubuntu-toolchain-r-test
        packages:
            - clang-5.0

install: export CXX="clang++-5.0" CC="clang-5.0"

language: cpp

compiler:
  - clang

script:
  - mkdir out
  - cd out
  - cmake ../test/
  - make
  - ./dux_fixed_test